resourceType: Application
resources:
  - description: >-
      Requests weather data from an external API to populate a personal weather
      dashboard.
    filesPath: ./files
    globals:
      - cloudOnly: true
        description: >-
          The location (latitude, longitude) that will be used when requesting
          weather data.
        json: '"39.108335,-84.509212"'
        key: gps_location
      - cloudOnly: true
        description: >-
          The OpenWeatherMap API key. Get your key here:
          https://openweathermap.org/api
        json: '"YOUR_API_KEY"'
        key: api_key
    id: ~losant-application-weatherStation-0~
    name: Weather Station
    readmePath: ./README.md
version: 1
