resourceType: Application
resources:
  - appliedTemplateIds: []
    blobUrlTTL: 86400
    description: OEE calculations and dashboards for simulated paper machines.
    filesPath: ./files
    globals: []
    id: ~losant-application-applicationOverallEquipmentEffectivenessOee-0~
    name: Overall Equipment Effectiveness (OEE)
    readmePath: ./README.md
version: 1
